"""
generators/hooks.py — Pools de hooks stop-scroll TikTok par thème.
Max 8 mots. Ton réel, vécu, humain. Jamais abstrait.
"""
import hashlib

_HOOK_POOLS: dict[str, list[str]] = {

    "retour": [
        "Il est revenu 3 mois plus tard.",
        "Elle a rappelé sans prévenir.",
        "J'avais arrêté d'attendre.",
        "Il a écrit après des mois.",
        "Son message a tout remis en question.",
        "Il a sonné à ma porte ce soir.",
        "Elle a envoyé un message à 2h.",
        "Il m'a dit qu'il s'était trompé.",
        "J'avais déjà tourné la page.",
        "Il a réapparu quand j'allais bien.",
        "Elle est revenue comme si rien n'était.",
        "Son prénom s'est affiché après 6 mois.",
        "Il m'a demandé pardon ce soir-là.",
        "Elle a recommencé à regarder mes stories.",
        "Il a liké ma photo 8 mois après.",
        "Elle m'a retrouvée sur un autre réseau.",
        "Il a repris contact le soir de son anniversaire.",
        "J'avais supprimé son numéro.",
        "Elle a revu quelqu'un… puis m'a rappelé.",
        "Il revenait toujours au pire moment.",
        "J'avais refait ma vie. Il a rappelé.",
        "Son premier message : « Tu vas bien ? »",
        "Elle m'a écrit après notre dispute finale.",
        "Il a rouvert une conversation vieille de 1 an.",
        "Elle a demandé si je pensais encore à elle.",
        "J'avais effacé ses photos. Il est revenu.",
        "Il a vu mes stories 5 nuits d'affilée.",
        "Son retour a tout compliqué.",
        "Elle avait refait sa vie. Et alors ?",
        "Il m'a dit qu'il n'était pas passé à autre chose.",
        "Je croyais avoir tout réglé dans ma tête.",
        "Elle m'a appelée un dimanche matin.",
        "Son message : « On peut se parler ? »",
        "Il a repris contact via un ami commun.",
        "Elle m'a envoyé une chanson sans rien dire.",
        "J'avais bloqué. Il a créé un nouveau compte.",
        "Il est arrivé au moment où j'aimais quelqu'un d'autre.",
        "Elle pleurait dans ses messages.",
        "Il disait qu'il avait changé.",
        "Elle m'a laissé un message vocal de 4 minutes.",
        "Je n'aurais pas dû décrocher.",
        "3 mois sans nouvelles. Puis ça.",
        "Il a débarqué avec des fleurs.",
        "Son retour m'a tout fait revivre.",
        "Elle avait un nouveau copain. Ça n'a pas duré.",
        "Il voulait tout recommencer à zéro.",
        "J'ai dit non. Et après j'ai regretté.",
        "Elle m'a dit qu'elle pensait à moi tous les jours.",
        "Son retour m'a tué plus que sa rupture.",
        "J'avais appris à vivre sans lui.",
        "Elle m'a fixé un rendez-vous.",
        "Il est revenu en prétextant un objet oublié.",
        "Je l'ai reconnu dans la rue 7 mois après.",
        "Elle passait devant chez moi par hasard.",
        "Il a lâché « je t'aime encore » par texto.",
        "On s'est vus et tout est remonté.",
        "Elle m'a demandé si j'étais libre.",
        "J'ai failli lui répondre. J'ai attendu.",
        "Il a mis 3 heures pour envoyer deux mots.",
        "Son retour m'a appris que j'avais guéri.",
        "Elle a pleuré. J'ai tenu bon.",
        "Il était avec quelqu'un. Et il m'écrivait quand même.",
        "Je savais qu'il allait revenir.",
        "Son retour : la pire et la meilleure chose.",
        "Elle a dit : « J'aurais dû rester. »",
        "J'attendais ce message depuis 4 mois.",
        "Il a dit qu'il ne pouvait plus sans moi.",
        "Je n'ai pas répondu tout de suite.",
        "Elle a partagé un souvenir qu'on avait ensemble.",
        "Son retour m'a perturbée pendant des semaines.",
        "J'avais fait le deuil. Et alors il a écrit.",
        "Il a attendu que j'aille mieux pour revenir.",
        "Elle m'a dit que personne ne me remplacerait.",
        "Son message : «Tu me manques depuis le début.»",
        "Il m'a demandé pardon une deuxième fois.",
        "J'avais construit quelque chose sans lui.",
        "Elle a recommencé à m'appeler par mon surnom.",
        "Il voulait me parler. J'ai refusé.",
        "Son retour a rouvert quelque chose que je croyais fermé.",
        "3 ans après, son numéro sur mon écran.",
        "Elle m'a promis que cette fois c'était différent.",
        "Je savais que je n'aurais pas dû ouvrir.",
        "Il a repris exactement là où on s'était arrêtés.",
        "Elle avait l'air de n'avoir pas dormi.",
        "Son message est arrivé le soir de ma date.",
        "J'avais commencé à l'oublier pour de vrai.",
        "Il a rappelé le jour de ma fête.",
        "Elle m'a dit qu'elle avait besoin de me voir.",
        "Son retour m'a fait tout remettre en question.",
        "Il m'avait quitté par texto. Il est revenu en personne.",
        "J'avais supprimé tout ce qui me rappelait à elle.",
        "Elle a remis la même photo de profil qu'avant.",
        "Son retour n'a pas changé ce qui s'était passé.",
        "Je l'ai revu une seule fois. Ça m'a suffi.",
        "Elle m'a demandé si on pouvait recommencer.",
        "Il avait fait ses valises. Et il était là.",
        "Son prénom encore. Après tout ce temps.",
        "J'avais dit que c'était terminé. Et là.",
        "Elle a dit qu'elle avait eu tort.",
        "Il est revenu juste quand je n'en avais plus besoin.",
    ],

    "tromperie": [
        "Mais je sentais qu'il mentait.",
        "Il était au téléphone à 2h du matin.",
        "Elle avait verrouillé ses messages.",
        "J'ai vu un prénom que je ne connaissais pas.",
        "Il rentrait tard sans raison.",
        "Elle a changé son mot de passe.",
        "J'ai trouvé des messages que je n'aurais pas dû voir.",
        "Il souriait à son téléphone et s'arrêtait quand j'arrivais.",
        "Elle avait dit qu'elle était avec une amie.",
        "J'ai entendu une voix dans son téléphone.",
        "Il avait une deuxième boîte mail.",
        "Elle portait un parfum que je ne lui avais pas offert.",
        "J'ai vu ses notifications s'activer à 23h.",
        "Il effaçait ses messages devant moi.",
        "Elle n'arrivait pas à me regarder dans les yeux.",
        "J'ai reconnu une voiture garée devant chez lui.",
        "Il avait un téléphone que je ne connaissais pas.",
        "Elle avait ajouté un contact sous un faux prénom.",
        "J'ai retrouvé un ticket de restaurant pour deux.",
        "Son comportement avait changé du jour au lendemain.",
        "Il prenait des appels en sortant de la pièce.",
        "Elle avait mis un code sur ses photos.",
        "J'ai su en voyant son visage que c'était vrai.",
        "Il avait menti sur où il était ce soir-là.",
        "Elle disait « on travaillait tard ».",
        "Je l'ai vu dans un endroit où il ne devait pas être.",
        "Elle m'a menti en face pendant des mois.",
        "J'ai remarqué qu'il désactivait sa localisation.",
        "Elle avait deux versions de la même soirée.",
        "Son explication n'avait aucun sens.",
        "J'avais des doutes depuis longtemps.",
        "Il effaçait son historique chaque soir.",
        "Elle n'emportait plus son téléphone quand je la rejoignais.",
        "J'ai vu son sourire quand il a reçu ce message.",
        "Il ne me répondait plus dans la journée.",
        "Elle a commencé à aller à la salle le soir.",
        "J'ai entendu quelqu'un lui écrire « tu m'as manqué ».",
        "Il a eu l'air paniqué quand j'ai pris son téléphone.",
        "Elle m'envoyait des messages avec des fautes inhabituelles.",
        "J'ai reconnu la coupe de cheveux d'une autre sur sa photo.",
        "Il avait retourné son téléphone face contre la table.",
        "Elle avait oublié de déconnecter son compte.",
        "J'ai trouvé un message qu'elle croyait avoir supprimé.",
        "Il ne m'avait pas dit qu'il était passé la voir.",
        "Elle avait mentionné un prénom que je n'avais jamais entendu.",
        "J'ai su avant même de chercher.",
        "Il avait une énergie différente quand il rentrait.",
        "Elle n'avait plus le même regard.",
        "J'ai trouvé des photos que je ne connaissais pas.",
        "Il pleurait. Et moi, je n'y croyais plus.",
        "Elle a tout nié jusqu'au bout.",
        "Son alibi n'a pas tenu 10 minutes.",
        "J'ai demandé une seule fois. Il a nié.",
        "Elle lui écrivait depuis des mois.",
        "J'ai compris en lisant entre les lignes.",
        "Il savait que je savais. Il a quand même continué.",
        "Elle m'a regardée mentir à ma propre famille.",
        "J'aurais préféré ne jamais savoir.",
        "Il avait tout caché parfaitement. Presque.",
        "Elle l'avait présenté comme un « collègue ».",
        "J'ai entendu sa voix dans la pièce d'à côté.",
        "Il m'avait dit qu'il était seul ce week-end.",
        "Elle avait prévu un voyage avec lui.",
        "J'ai retrouvé un message d'amour dans une poche.",
        "Il l'avait tagguée. Et effacé juste après.",
        "Elle lui avait offert quelque chose.",
        "J'ai vu une réservation pour deux.",
        "Il avait choisi. Sans me le dire.",
        "Elle avait une vie que j'ignorais.",
        "J'ai mis des semaines à accepter ce que j'avais vu.",
        "Il m'a dit que je m'inventais des choses.",
        "Elle m'a fait douter de moi-même.",
        "J'ai failli lui pardonner. Failli.",
        "Il avait dissimulé ça pendant 1 an.",
        "Elle pleurait en me demandant pardon.",
        "J'ai tout su un vendredi soir.",
        "Son téléphone a sonné. Il a quitté la pièce.",
        "J'ai trouvé une conversation que j'aurais voulu ne jamais voir.",
        "Il avait un double vie, là, devant moi.",
        "Elle m'avait dit qu'il ne s'était rien passé.",
        "J'ai continué à faire semblant pendant 2 semaines.",
        "Il savait ce qu'il faisait. Et il a continué.",
        "Elle avait osé le ramener dans ma maison.",
        "J'ai pleuré une nuit entière avant d'agir.",
        "Il m'a dit : « Tu as imaginé. »",
        "Elle avait tout effacé. Mais j'avais vu.",
        "J'ai demandé une preuve. Il m'en a donné une.",
        "Son mensonge était préparé depuis des semaines.",
        "Elle disait qu'elle était malheureuse avec moi.",
        "J'ai su que tout était faux.",
        "Il m'a menti le jour de mon anniversaire.",
        "Elle n'avait jamais rompu avec l'autre.",
        "J'ai compris en voyant son sourire.",
        "Il avait gardé son ancienne relation secrète.",
        "Elle le voyait pendant que je travaillais.",
        "J'ai décidé de ne rien dire. D'abord.",
        "Son silence confirmait tout ce que je savais.",
        "J'avais besoin d'entendre un « non ». Je n'ai pas eu.",
        "Elle m'a dit la vérité le soir où j'allais partir.",
        "Il avait inventé une histoire pour couvrir l'autre.",
        "J'aurais dû partir ce soir-là.",
    ],

    "silence": [
        "Il ne répondait plus.",
        "3 semaines sans un mot.",
        "Elle a disparu du jour au lendemain.",
        "Son silence m'a dit tout ce que ses mots ne disaient pas.",
        "J'envoyais des messages dans le vide.",
        "Il lisait. Il ne répondait pas.",
        "Elle a laissé tous mes appels sans réponse.",
        "J'avais besoin d'un mot. Rien.",
        "Il avait lu mon message depuis 3 jours.",
        "Elle n'était plus active depuis qu'on s'était disputés.",
        "J'ai attendu une réponse qui n'est pas venue.",
        "Son silence était plus cruel que ses mots.",
        "Il m'avait dit à demain. C'était il y a 2 semaines.",
        "Elle a tout coupé sans explication.",
        "Je ne savais pas si j'existais encore pour lui.",
        "Son silence me rendait folle.",
        "Elle avait disparu après notre dernière dispute.",
        "Il avait vu, lu, ignoré.",
        "Je m'expliquais son silence tous les jours différemment.",
        "Elle ne postait plus rien non plus.",
        "J'ai laissé un message vocal. Silence.",
        "Il avait arrêté de m'écrire le matin.",
        "Elle ne donnait plus de nouvelles depuis 10 jours.",
        "J'inventais des raisons pour qu'il ne réponde pas.",
        "Son silence était une réponse que je ne voulais pas entendre.",
        "Elle était en ligne. Elle ne m'écrivait pas.",
        "J'avais compté les jours. 18.",
        "Il m'avait laissée en plan au milieu d'une conversation.",
        "Elle ne m'avait plus contactée depuis le vendredi.",
        "Son absence m'était plus douloureuse que ses mots.",
        "Je ne savais plus si c'était fini ou pas.",
        "Il ne donnait aucun signe. Ni oui ni non.",
        "Elle avait juste disparu.",
        "J'attendais en regardant mon téléphone.",
        "Il avait vu mes stories. Toujours rien.",
        "Elle n'avait même pas lu.",
        "J'avais réécrit le même message 4 fois sans l'envoyer.",
        "Son silence durait depuis notre dernière soirée.",
        "Elle s'était connectée 3 fois. Rien.",
        "J'ai décidé de ne plus envoyer de message.",
        "Il n'avait pas répondu à mon happy birthday.",
        "Elle m'avait dit « je reviens » il y a une semaine.",
        "J'avais commencé à penser que c'était ma faute.",
        "Son silence m'a appris à ne plus attendre.",
        "Elle avait besoin d'espace. Pour combien de temps ?",
        "J'ai compris que son silence était sa réponse.",
        "Il ne m'avait pas bloquée. C'était pire.",
        "Elle avait arrêté d'aimer mes publications.",
        "J'avais analysé chaque mot de notre dernière conversation.",
        "Son absence dans ma vie créait un bruit constant.",
        "Elle était passée à autre chose. Moi non.",
        "J'ai mis des semaines à accepter que c'était fini.",
        "Il ne cherchait plus à me rassurer.",
        "Elle avait répondu à tout le monde sauf moi.",
        "J'ai coupé les notifications. Ça n'a rien changé.",
        "Son silence avait plus de sens que ses messages.",
        "Elle avait dit qu'elle était juste débordée.",
        "J'ai arrêté de compter les heures.",
        "Il lisait mais ne tapait rien.",
        "Elle avait ouvert notre conversation. Puis refermée.",
        "J'avais besoin d'un signe. N'importe lequel.",
        "Son silence entre deux messages durait des jours.",
        "Elle n'avait pas répondu à ma demande.",
        "J'avais refusé d'accepter que c'était du ghosting.",
        "Il avait répondu à un emoji. Rien d'autre.",
        "Elle ne m'avait même pas vue en ligne.",
        "J'ai relu nos anciens messages pour comprendre.",
        "Son silence avait commencé doucement.",
        "Elle ne répondait plus aux vocaux.",
        "J'ai laissé 2 messages. Vus. Pas de réponse.",
        "Il ne revenait pas sur notre dernière dispute.",
        "Elle avait mis le statut « occupée ».",
        "J'ai essayé d'appeler. Messagerie directement.",
        "Son silence m'avait appris à ne plus rien espérer.",
        "Elle avait cessé de regarder mes stories.",
        "J'ai envoyé un dernier message. Et attendu.",
        "Il m'avait répondu un mot après 5 jours.",
        "Elle n'était plus dans notre groupe de discussion.",
        "J'avais arrêté d'espérer. Il a répondu le lendemain.",
        "Son mutisme durait depuis notre première vraie dispute.",
        "Elle avait dit qu'elle avait besoin de réfléchir.",
        "Je m'étais dit : s'il ne répond pas demain, c'est fini.",
        "Son silence était pire que si on s'était disputés.",
        "Elle ne me lisait plus.",
        "J'avais décidé de ne plus être disponible.",
        "Il ne m'avait plus dit bonjour depuis des jours.",
        "Elle avait répondu à mes 3 messages par un « ok ».",
        "J'ai lu « Lu à 23h14 ». Plus rien depuis.",
        "Son silence s'est installé progressivement.",
        "Elle ne mentionnait plus de projets avec moi.",
        "J'ai compris que le silence, ça dit tout.",
        "Il était là, mais absent.",
        "Elle me répondait en retard. De plus en plus.",
        "J'ai arrêté d'envoyer des messages le premier.",
        "Son silence après ce que j'avais dit m'a tué.",
        "Elle avait répondu à mon message 3 jours après.",
        "J'avais dit quelque chose. Il n'avait pas répondu.",
        "Son absence en ligne était une présence dans ma tête.",
        "Elle ne tapait plus rien. Je voyais les trois points. Puis rien.",
        "J'ai attendu jusqu'à minuit.",
    ],

    "ex": [
        "Je n'arrivais pas à l'oublier.",
        "Sa photo a refait surface.",
        "J'ai croisé son frère dans la rue.",
        "Elle pensait encore à lui chaque matin.",
        "Je regardais son profil sans le vouloir.",
        "Il avait quelqu'un de nouveau.",
        "Elle avait l'air heureuse sur sa photo.",
        "J'avais supprimé son numéro mais je le connaissais par cœur.",
        "Il avait passé à autre chose plus vite que moi.",
        "Elle était toujours dans ma tête.",
        "Je revoyais les mêmes endroits.",
        "Il avait l'air d'aller bien. Moi non.",
        "Sa nouvelle relation m'a tout remis en tête.",
        "J'essayais de sortir. Je pensais à elle.",
        "Il avait changé de ville. Ça ne changeait rien pour moi.",
        "Elle avait refait sa vie. J'avais du mal.",
        "Je ne savais pas si j'étais en train de guérir.",
        "Son prénom revenait dans chaque conversation.",
        "Il avait dit qu'il était mieux sans moi.",
        "Elle avait changé. Mais je m'en souvenais autrement.",
        "J'avais gardé une photo cachée.",
        "Il dormait encore dans mes rêves.",
        "Elle m'avait quitté sans vraiment d'explication.",
        "J'avais besoin de comprendre pourquoi ça n'avait pas marché.",
        "Son souvenir s'accrochait à tout.",
        "Il avait été ma référence pour tout.",
        "Elle m'avait dit qu'elle ne m'avait jamais aimé.",
        "J'avais relu notre dernière dispute cent fois.",
        "Son nouveau partenaire me ressemblait.",
        "Elle continuait à vivre comme si rien n'était.",
        "J'avais essayé de rencontrer quelqu'un. Ça n'allait pas.",
        "Il m'avait dit des mots que je n'arrivais pas à effacer.",
        "Elle avait dit « on reste amis ». Mensonge.",
        "J'avais tourné la page. Presque.",
        "Il était passé dans ma rue.",
        "Elle avait commenté ma photo après 8 mois.",
        "J'avais besoin d'un signe que j'avais fait le bon choix.",
        "Son regard me revenait encore.",
        "Il m'avait rendu toutes mes affaires un mardi.",
        "Elle avait gardé des choses qui m'appartenaient.",
        "J'avais demandé à nos amis communs comment il allait.",
        "Son anniversaire approchait. Je savais la date par cœur.",
        "Elle avait dit que je lui avais fait du mal.",
        "J'avais besoin de lui dire une dernière chose.",
        "Il avait bloqué puis débloqué sans raison.",
        "Elle m'avait donné un prénom dans ma tête.",
        "J'avais arrêté de chercher des ressemblances.",
        "Son souvenir était plus fort que sa présence.",
        "Il avait commencé à sortir. Sans moi.",
        "Elle ne regardait plus mes stories depuis la rupture.",
        "J'essayais d'être quelqu'un de différent.",
        "Il m'avait dit que j'étais la meilleure chose.",
        "Elle avait dit qu'on était trop différents.",
        "J'avais arrêté d'attendre qu'il regrette.",
        "Il avait quelqu'un. C'était visible.",
        "Elle m'avait effacé partout. Sauf dans sa tête.",
        "J'avais besoin d'entendre que j'avais compté.",
        "Son nom me paralysait encore.",
        "Il avait tout réécrit après moi.",
        "Elle avait effacé nos photos.",
        "J'avais vu sa nouvelle relation durer.",
        "Son profil ne me disait plus rien. Mais je revenais.",
        "Il avait trouvé quelqu'un qui lui ressemblait.",
        "Elle avait avancé. J'essayais de faire pareil.",
        "J'avais arrêté de comparer.",
        "Son souvenir ne disparaissait pas.",
        "Il avait dit du mal de moi après.",
        "Elle avait revu tous nos amis communs sans moi.",
        "J'avais besoin de tourner la page pour de vrai.",
        "Son absence dans ma vie créait un vide.",
        "Il ne m'avait jamais vraiment dit au revoir.",
        "Elle m'avait quitté par message.",
        "J'avais compris la raison de notre fin trop tard.",
        "Son absence m'avait libéré sans que je le réalise.",
        "Il avait laissé une trace dans tout ce que je faisais.",
        "Elle avait refait tout ce qu'on faisait ensemble.",
        "J'avais guéri. Mais le souvenir restait.",
        "Son départ m'avait appris quelque chose.",
        "Il avait dit que j'étais trop attaché.",
        "Elle avait trouvé quelqu'un plus stable.",
        "J'avais arrêté d'en vouloir à quelqu'un.",
        "Son image s'effaçait enfin.",
        "Il m'avait laissé avec des demi-réponses.",
        "Elle ne m'avait pas invité à son anniversaire.",
        "J'avais décidé de ne plus chercher à comprendre.",
        "Son souvenir me rendait meilleur.",
        "Il avait refait ma vie à travers d'autres.",
        "Elle avait dit une dernière fois qu'elle était désolée.",
        "J'avais mis un an. Mais j'étais passé à autre chose.",
        "Son absence avait tout changé en moi.",
        "Il n'existait plus sur mes réseaux.",
        "Elle avait tourné la page bien avant moi.",
        "J'avais enfin arrêté de regarder son profil.",
        "Son prénom ne me faisait plus rien.",
        "Il avait existé. Et ça m'avait suffi.",
        "Elle avait fait partie de moi. Et ça ne change pas.",
        "J'avais compris que certaines personnes passent.",
        "Son passage dans ma vie n'était pas une erreur.",
        "Il avait été là au bon moment.",
    ],

    "jalousie": [
        "Elle était plus belle que moi.",
        "Il comparait sans le dire.",
        "J'avais peur de la perdre à cause d'elle.",
        "Elle commentait toutes ses photos.",
        "Il parlait d'elle trop souvent.",
        "J'avais vu qu'il l'avait ajoutée.",
        "Elle était son type.",
        "Il mentionnait son prénom depuis des semaines.",
        "J'avais vu leurs échanges par accident.",
        "Elle était toujours là quand j'étais pas là.",
        "Il passait du temps avec elle sans me le dire.",
        "J'avais besoin de savoir si j'étais remplacée.",
        "Elle faisait semblant de ne pas exister.",
        "Il avait une façon particulière de lui parler.",
        "J'avais demandé. Il avait dit « c'est juste une amie ».",
        "Elle lui écrivait tous les soirs.",
        "J'avais vu qu'il avait liké ses anciennes photos.",
        "Il m'avait dit de ne pas me faire des idées.",
        "Elle était présente dans chaque sortie.",
        "J'avais du mal à faire confiance.",
        "Il passait plus de temps à lui répondre qu'à moi.",
        "Elle savait des choses sur lui que je ne savais pas.",
        "J'avais analysé chaque interaction.",
        "Il riait différemment quand elle était là.",
        "Elle lui avait offert quelque chose.",
        "J'avais vu son prénom dans la liste des appels.",
        "Il l'avait raccompagnée seul.",
        "Elle avait une place dans sa vie que je ne comprenais pas.",
        "J'avais peur de sembler trop jalouse.",
        "Il m'avait dit que j'exagérais.",
        "Elle avait commencé à le suivre partout.",
        "J'avais vu leurs conversations supprimées.",
        "Il parlait d'elle différemment.",
        "Elle était mieux que moi sur un point. Plusieurs en fait.",
        "J'avais essayé de ne pas y penser.",
        "Il l'avait défendue contre moi.",
        "Elle était son passé qui revenait.",
        "J'avais senti que quelque chose avait changé.",
        "Il l'avait vue sans me le dire.",
        "Elle faisait partie de sa vie avant moi.",
        "J'avais besoin qu'il me rassure.",
        "Il ne le faisait pas.",
        "Elle était l'ombre que je ne pouvais pas ignorer.",
        "J'avais mis un nom sur ce que je ressentais.",
        "Il ne comprenait pas pourquoi ça me dérangeait.",
        "Elle l'appelait par son surnom.",
        "J'avais vu qu'il aimait encore ses photos.",
        "Il avait dit que je n'avais aucune raison de m'inquiéter.",
        "Elle était là avant moi.",
        "J'avais décidé de poser la question directement.",
        "Il avait hésité avant de répondre.",
        "Elle avait été plus qu'une amie.",
        "J'avais besoin d'une réponse honnête.",
        "Il n'arrivait pas à couper le lien.",
        "Elle savait qu'elle m'inquiétait.",
        "J'avais senti la tension quand ils étaient dans la même pièce.",
        "Il ne voulait pas se mettre à ma place.",
        "Elle me regardait différemment.",
        "J'avais fait semblant de ne pas y penser.",
        "Il me disait que j'avais tort. Et si j'avais raison ?",
        "Elle n'était pas juste une amie.",
        "J'avais appris à gérer. Pas à oublier.",
        "Il avait ri quand j'en avais parlé.",
        "Elle prenait trop de place.",
        "J'avais essayé de lui faire confiance à nouveau.",
        "Il ne voulait pas comprendre ce que ça me faisait.",
        "Elle l'avait vu sans que je le sache.",
        "J'avais décidé de lui poser des conditions.",
        "Il avait dit que c'était mon problème.",
        "Elle était devenue une source de conflit.",
        "J'avais arrêté de m'excuser de me sentir jalouse.",
        "Il m'avait dit de régler ça avec moi-même.",
        "Elle l'avait influencé sur certaines décisions.",
        "J'avais besoin d'une limite claire.",
        "Il ne voulait pas fixer cette limite.",
        "Elle était entre nous depuis le début.",
        "J'avais tenté d'en parler calmement.",
        "Il avait dit que je cherchais un problème.",
        "Elle avait répondu à son message public.",
        "J'avais senti que quelque chose me dérangerait toujours.",
        "Il m'aimait. Mais elle était là.",
        "Elle avait une connivence avec lui.",
        "J'avais compris que la jalousie avait du sens.",
        "Il ne voyait pas ce que je voyais.",
        "Elle le connaissait mieux que moi par moment.",
        "J'avais besoin qu'il fasse un choix.",
        "Il ne comprenait pas pourquoi c'était si grave.",
        "Elle n'était pas une ennemie. Mais pas une amie.",
        "J'avais appris à exprimer ce que je ressentais.",
        "Il avait finalement compris.",
        "Elle avait disparu de sa vie. Mais laissé des traces.",
        "J'avais eu raison de m'inquiéter.",
        "Il ne voulait pas l'admettre.",
        "Elle avait eu plus d'espace que moi dans sa tête.",
        "J'avais mis des mots dessus.",
        "Il m'avait dit que j'étais la seule.",
        "Elle était partie. Et j'avais enfin pu respirer.",
        "J'avais choisi de rester. Et d'apprendre à faire confiance.",
    ],

    "intuition": [
        "Je savais. Je ne comprenais pas comment.",
        "Mon ventre me disait quelque chose.",
        "J'avais un mauvais pressentiment depuis des jours.",
        "J'avais senti avant même qu'il parle.",
        "Elle ne mentait pas. Et pourtant je sentais quelque chose.",
        "Mon intuition n'avait jamais été aussi forte.",
        "J'avais ignoré ce signal la première fois.",
        "Je savais que cette relation allait mal finir.",
        "Mon corps avait réagi avant ma tête.",
        "Je n'avais aucune preuve. Juste cette certitude.",
        "J'avais senti quelque chose changer dans son regard.",
        "Mon instinct m'avait dit de partir.",
        "J'avais eu ce rêve deux fois avant que ça arrive.",
        "Une voix dans ma tête disait que c'était faux.",
        "Je n'arrivais pas à ignorer cette sensation.",
        "J'avais ressenti quelque chose avant même de savoir.",
        "Mon corps refusait ce que ma tête acceptait.",
        "Je sentais que cette personne me cachait quelque chose.",
        "J'avais cette impression de déjà-vu.",
        "Mon intuition avait toujours eu raison.",
        "Je l'avais senti avant même de le voir.",
        "J'avais su dès la première conversation.",
        "Mon pressentiment m'avait sauvé ce soir-là.",
        "Je m'étais éveillée à 3h sans raison. Il m'avait menti.",
        "J'avais ressenti quelque chose de bizarre ce matin-là.",
        "Mon instinct disait non. J'avais dit oui. Erreur.",
        "Je savais que cette situation allait se reproduire.",
        "J'avais ignoré le signe. Et tout avait mal tourné.",
        "Mon intuition était la seule chose qui ne m'avait jamais menti.",
        "Je ressentais les mensonges avant de les voir.",
        "J'avais eu la chair de poule pour rien. Ou pas.",
        "Mon corps m'avait alertée bien avant.",
        "Je savais que ce jour allait changer quelque chose.",
        "J'avais eu ce sentiment pendant 3 jours.",
        "Mon instinct m'avait dit de ne pas y aller.",
        "Je n'avais aucune logique pour expliquer ce que je ressentais.",
        "J'avais senti que cette personne avait besoin de moi.",
        "Mon pressentiment était arrivé la nuit.",
        "Je savais que quelque chose se passait, même loin.",
        "J'avais décidé de faire confiance à ce que je ressentais.",
        "Mon intuition avait reconnu quelque chose dans son comportement.",
        "Je n'avais rien vu. Mais j'avais tout su.",
        "J'avais eu cette pensée une seule fois. Et elle s'était réalisée.",
        "Mon instinct m'avait dit que cette fois c'était différent.",
        "Je savais avant même qu'il ouvre la bouche.",
        "J'avais ressenti sa présence avant qu'il arrive.",
        "Mon corps avait su qu'il partait.",
        "Je ne dormais pas. Et mon pressentiment tournait dans ma tête.",
        "J'avais fait un rêve clair. Deux jours après c'était réel.",
        "Mon intuition m'avait dit de ne pas lire ses messages.",
        "Je savais que cette rencontre avait un sens.",
        "J'avais eu une certitude soudaine au mauvais moment.",
        "Mon pressentiment m'avait dit d'attendre.",
        "Je n'avais pas suivi mon instinct. Et j'avais regretté.",
        "J'avais senti que l'énergie avait changé entre nous.",
        "Mon intuition ne se trompait jamais sur les gens.",
        "Je savais dès le début que ça finirait comme ça.",
        "J'avais ressenti quelque chose la première nuit.",
        "Mon corps refusait d'aller à ce rendez-vous.",
        "Je savais qu'il y avait quelqu'un d'autre.",
        "J'avais senti sa distance avant qu'il me la dise.",
        "Mon pressentiment cette nuit-là était trop fort pour l'ignorer.",
        "Je savais que cette décision était la bonne, même si elle faisait mal.",
        "J'avais senti que quelque chose allait m'arriver ce jour-là.",
        "Mon instinct m'avait guidée vers la bonne personne.",
        "Je savais que cette période allait se terminer.",
        "J'avais ressenti une paix soudaine avant la tempête.",
        "Mon intuition m'avait dit que c'était la dernière fois.",
        "Je savais que je devais partir. Avant même qu'il parte.",
        "J'avais eu des signes pendant des jours.",
        "Mon corps avait senti l'urgence avant ma tête.",
        "Je savais que ce silence n'était pas normal.",
        "J'avais un doute depuis le début. Il s'était confirmé.",
        "Mon instinct m'avait dit de ne pas croire à sa version.",
        "Je savais que c'était trop beau.",
        "J'avais senti que ce moment allait tout changer.",
        "Mon pressentiment sur cette personne s'était révélé exact.",
        "Je n'avais pas de preuve. Juste cette certitude dans le ventre.",
        "J'avais su que quelque chose n'allait pas avant de voir.",
        "Mon intuition m'avait dit de rester.",
        "Je savais que cette attente en valait la peine.",
        "J'avais senti quelque chose de différent dans son sourire.",
        "Mon instinct m'avait sauvée d'une erreur.",
        "Je ne l'avais pas écoutée. Et ça s'était vu.",
        "J'avais appris à faire confiance à cette voix.",
        "Mon intuition était la seule boussole qui ne m'avait pas abandonnée.",
        "Je savais que cette relation allait m'apprendre quelque chose.",
        "J'avais ressenti quelque chose en lisant son message.",
        "Mon corps avait réagi à son nom.",
        "Je n'avais pas compris ce pressentiment sur le moment.",
        "J'avais appris à reconnaître les signaux.",
        "Mon intuition avait toujours précédé la réalité.",
        "Je savais que ce n'était pas fini.",
        "J'avais senti que ce n'était pas un hasard.",
        "Mon instinct était plus honnête que ses mots.",
        "Je savais que cette nuit allait être décisive.",
        "J'avais ce pressentiment depuis notre premier message.",
        "Mon intuition : ma seule certitude dans le doute.",
    ],

    "destin": [
        "On s'est croisés 3 fois avant de se parler.",
        "Ce lien résiste à tout.",
        "On s'est perdus 3 fois. Et retrouvés.",
        "Destinés ou pas ?",
        "On était dans la même ville depuis 2 ans sans le savoir.",
        "Il était censé partir ce soir-là. Il est resté.",
        "On s'est rencontrés par une chaîne de hasards.",
        "Ce n'était pas censé arriver. Et pourtant.",
        "On avait des amis communs depuis des années.",
        "Je n'étais pas supposée aller à ce rendez-vous.",
        "Son numéro est arrivé dans ma vie deux fois.",
        "On avait failli se rencontrer 1 an avant.",
        "Il était là au pire moment de ma vie.",
        "Elle avait dit un jour que je serais dans sa vie.",
        "On s'était vus en rêve avant de se rencontrer.",
        "Ce lien existait avant qu'on comprenne pourquoi.",
        "Il n'avait pas été invité ce soir. Et pourtant.",
        "Elle était la personne que je cherchais sans le savoir.",
        "On s'était séparés et recrouverts 3 fois.",
        "Ce n'était pas un hasard que l'on soit là en même temps.",
        "Il avait pris un autre chemin et c'était celui que je prenais.",
        "Elle était la seule personne à qui j'avais parlé ce jour-là.",
        "On avait les mêmes cicatrices sans se connaître.",
        "Il était arrivé au bon moment. Trop bon pour être faux.",
        "Ce lien était là avant les mots.",
        "Elle m'avait reconnu sans me connaître.",
        "On partageait des souvenirs de villes différentes.",
        "Il avait eu la même pensée au même moment.",
        "Ce n'était pas possible statistiquement.",
        "Elle avait rêvé de moi avant de me voir.",
        "On avait évité de se rencontrer pendant des années.",
        "Il était apparu juste après que j'avais demandé un signe.",
        "Ce lien m'avait surpris moi-même.",
        "Elle était différente de tout ce que j'attendais.",
        "On s'était compris sans se l'expliquer.",
        "Il m'avait dit une phrase que j'attendais depuis longtemps.",
        "Ce lien résistait à la distance.",
        "Elle était revenue à chaque tournant.",
        "On avait chacun refait notre vie. Et on s'était retrouvés.",
        "Il y avait une logique dans nos retrouvailles.",
        "Ce n'était pas un conte. C'était réel.",
        "Elle avait attendu sans savoir qu'elle attendait.",
        "On avait les mêmes peurs aux mêmes moments.",
        "Il avait été là sans que je le lui demande.",
        "Ce lien ne ressemblait à rien de ce que j'avais connu.",
        "Elle était là dans les bons et les mauvais moments.",
        "On s'était retrouvés sans l'avoir prévu.",
        "Il avait tout raté, sauf moi.",
        "Ce lien avait survécu à tout ce qui l'avait attaqué.",
        "Elle avait dit un jour : « On se retrouvera. »",
        "On avait partagé sans savoir qu'on partageait.",
        "Il avait compris des choses sur moi que je ne savais pas.",
        "Ce n'était pas le hasard. J'en étais certaine.",
        "Elle avait été là à chaque rupture.",
        "On avait vécu la même chose à des milliers de kilomètres.",
        "Il était revenu à chaque fois que je l'avais oublié.",
        "Ce lien avait une mémoire.",
        "Elle avait fait partie de ma vie sans que j'y aie été invitée.",
        "On s'était reconnus avant de se connaître.",
        "Il était ma réponse sans que j'aie posé de question.",
        "Ce lien m'avait appris ce que je cherchais.",
        "Elle avait dit des mots qui m'avaient changé.",
        "On s'était retrouvés là où tout avait commencé.",
        "Il avait eu la même intuition que moi le même soir.",
        "Ce n'était pas une coïncidence. C'était une répétition.",
        "Elle était quelqu'un de précis dans ma vie.",
        "On avait des dates en commun sans le savoir.",
        "Il avait dit : « Je t'attendais. »",
        "Ce lien n'avait pas de nom mais avait de la réalité.",
        "Elle était la personne que j'aurais choisie.",
        "On n'avait pas le même parcours. Et pourtant.",
        "Il m'avait dit que ça l'avait frappé dès la première fois.",
        "Ce lien était là avant d'exister.",
        "Elle m'avait protégé sans le savoir.",
        "On se comprenait sans mots.",
        "Il était la dernière personne à qui je m'étais attendu.",
        "Ce n'était pas prévu. C'était mieux.",
        "Elle avait rendu réel quelque chose que je croyais impossible.",
        "On avait eu peur au même moment.",
        "Il m'avait dit quelque chose que personne d'autre ne savait.",
        "Ce lien était plus fort que toutes les raisons de s'en aller.",
        "Elle avait vécu ce que j'avais vécu avant de me rencontrer.",
        "On s'était cherchés sans le savoir pendant des années.",
        "Il était arrivé comme une évidence.",
        "Ce n'était pas une relation ordinaire.",
        "Elle était là quand personne d'autre n'était là.",
        "On avait un lien que ni le temps ni la distance n'avaient rompu.",
        "Il m'avait dit que j'avais changé quelque chose pour lui.",
        "Ce lien : inexplicable. Mais indéniable.",
        "Elle était dans ma vie depuis le début sans que je m'en rende compte.",
        "On avait nos vies séparées. Mais ce lien restait.",
        "Il était revenu même quand je lui avais dit de partir.",
        "Ce n'était pas de l'amour au sens ordinaire.",
        "Elle m'avait compris mieux que moi-même.",
        "On avait traversé des choses qui auraient séparé n'importe qui.",
        "Il avait été là lors de mon pire moment.",
        "Ce lien survivait à tout ce qui l'avait mis à l'épreuve.",
        "Elle était la réponse à une question que je n'avais pas posée.",
        "On s'était perdus. Et retrouvés. Et ça avait tout son sens.",
    ],
}


def _sample_hooks(theme_id: str, today: str, n: int = 6) -> list[str]:
    """Return n deterministic hooks from the pool for theme_id + today."""
    pool = _HOOK_POOLS.get(theme_id, [])
    if not pool:
        return []
    h = int(hashlib.md5(f"hooks-{theme_id}-{today}".encode()).hexdigest(), 16)
    indices = []
    seen: set[int] = set()
    step = max(1, len(pool) // (n * 2))
    for i in range(n * 4):
        idx = (h + i * step + i * i) % len(pool)
        if idx not in seen:
            seen.add(idx)
            indices.append(idx)
        if len(indices) >= n:
            break
    return [pool[i] for i in indices[:n]]
